//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projrect_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class item1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public item1()
        {
            this.sell_premission = new HashSet<sell_premission>();
            this.supply_premision = new HashSet<supply_premision>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
        public Nullable<int> quantity { get; set; }
        public string measure_unit { get; set; }
        public Nullable<int> store_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sell_premission> sell_premission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supply_premision> supply_premision { get; set; }
    }
}
