//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projrect_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sell_premission
    {
        public int customer_id { get; set; }
        public int store_id { get; set; }
        public string item_id { get; set; }
        public int premission_no { get; set; }
        public Nullable<System.DateTime> premmision_date { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual item1 item1 { get; set; }
        public virtual store store { get; set; }
    }
}
